---
- name: Provision Ansible controller with SSH key for remote
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../group_vars/all/vault.yml
  vars:
    ssh_key_name: ansible_remote
    ssh_key_vault_path: "{{ vault_base_path }}/ansible"

  tasks:
    - debug:
        var: aws_profile

    - debug:
        var: vault_base_path

    - debug:
        var: ssh_key_vault_path

  roles:
    - companieshouse.general.ssh_key
