---
- name: Provision Ansible controller with SSH key for remote
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../group_vars/all/bind.yml
    - ../group_vars/all/vault.yml

  vars:
    ssh_key_name: ansible_remote
    ssh_key_vault_path: "{{ vault_base_path }}/secret"

  pre_tasks:
    - debug:
        var: ssh_key_vault_path

    - debug:
        var: vault_base_path

    - debug:
        var: aws_profile

    - debug:
        msg: "{{ lookup('env', 'VAULT_ADDR') }}"

    - debug:
        msg: "ROLE_ID present"
      when: lookup('env', 'ANSIBLE_HASHI_VAULT_ROLE_ID') | length > 0

    - debug:
        msg: "SECRET_ID present"
      when: lookup('env', 'ANSIBLE_HASHI_VAULT_SECRET_ID') | length > 0

  roles:
    - role: companieshouse.general.ssh_key
