---
- name: Provision Ansible SSH key
  import_playbook: ansible-ssh-key.yml

  pre_tasks:
    - debug:
        msg: "RECORD_UPDATE_TEST"

- name: Deploy DNS Zone Files
  hosts: tag_Name_bind_ns1
  remote_user: ec2-user
  become: true
  gather_facts: false

  pre_tasks:
    - name: Verify SSH user
      command: whoami
      register: whoami_out

    - debug:
        var: whoami_out.stdout

  vars:
    bind_service_validate_zones: true

  vars_files:
    - ../group_vars/all/bind.yml
    - ../group_vars/all/vault.yml

  roles:
    - bind_service
