---
- name: Provision Ansible SSH key
  import_playbook: ansible-ssh-key.yml

- name: Deploy DNS Zone Files
  hosts: tag_Name_bind_ns1
  become: true
  gather_facts: false

  vars:
    bind_service_validate_zones: true

  vars_files:
    - ../group_vars/all/bind.yml
    - ../group_vars/all/vault.yml

  roles:
    - bind_service
