---
- name: Provision Ansible controller with SSH key for remote
  hosts: localhost

  pre_tasks:
  - name: PROVE WHICH PLAYBOOK IS RUNNING
    debug:
      msg: "vault-update branch playbook"


  roles:
    - role: companieshouse.general.ssh_key
      vars:
        ssh_key_name: ansible_remote
        ssh_key_vault_path: "{{ vault_base_path }}/ansible"
