---
- name: Provision Ansible controller with SSH key for remote
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
        ssh_key_name: ansible_remote
        ssh_key_vault_path: "/team-unix-storage/heritage-development-eu-west-2/bind/ansible"

  pre_tasks:
    - debug:
        var: aws_profile

    - debug:
        var: vault_base_path

    - debug:
        msg: "{{ vault_base_path | default('UNDEFINED') }}/ansible"

  roles:
    - role: companieshouse.general.ssh_key
#      vars:
#        ssh_key_name: ansible_remote
#        ssh_key_vault_path: "/team-unix-storage/heritage-development-eu-west-2/bind/ansible"
#        ssh_key_vault_path: "{{ vault_base_path }}/ansible"
