---
- name: Find matching zone definitions
  ansible.builtin.set_fact:
    bind_service_matching_zones: >-
      {{
        bind_service_zone_definitions.zones
        | selectattr('environment', 'equalto', bind_environment)
        | list
      }}

- name: Deploy zone files
  ansible.builtin.include_tasks: deploy_single_zone.yml
  loop: "{{ bind_service_matching_zones }}"
  loop_control:
    loop_var: zone_definition
