---
- name: Create zone directories
  ansible.builtin.file:
    path: "{{ bind_zones_dir }}/{{ item.file | dirname }}"
    state: directory
    owner: "{{ bind_zones_owner }}"
    group: "{{ bind_zones_group }}"
    mode: "{{ bind_zones_directory_mode }}"
  loop: "{{ bind_service_matching_zones }}"

- name: Deploy zone files
  ansible.builtin.include_tasks: deploy_single_zone.yml
  loop: "{{ bind_service_matching_zones }}"
  loop_control:
    loop_var: zone_definition
