---
- name: Acquire lock
  ansible.builtin.file:
    path: "{{ bind_service_lock_file }}"
    state: touch
    owner: "{{ bind_service_lock_owner }}"
    group: "{{ bind_service_lock_group }}"
    mode: "{{ bind_service_lock_mode }}"
  changed_when: false

- name: Load zones.yml
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../bind-zone-data/groups/zones/zones.yml"
    name: bind_service_zone_definitions

- name: Select zones for current environment
  ansible.builtin.set_fact:
    bind_service_matching_zones: >-
      {{
        bind_service_zone_definitions.zones
        | selectattr('environment', 'equalto', bind_environment)
        | list
      }}

- name: Deploy zone files
  ansible.builtin.include_tasks: deploy_zone_files.yml

- name: Validate zones
  ansible.builtin.include_tasks: validate.yml
  when: bind_service_validate_zones | bool

- name: Release lock
  ansible.builtin.file:
    path: "{{ bind_service_lock_file }}"
    state: absent
  changed_when: false
