---
- name: Validate zone file exists
  ansible.builtin.stat:
    path: "{{ bind_service_zone_dir }}/{{ zone_item.file }}"
  register: bind_service_zone_file

- name: Assert zone file exists
  ansible.builtin.assert:
    that:
      - bind_service_zone_file.stat.exists
    fail_msg: >-
      Zone file not found:
      {{ bind_service_zone_dir }}/{{ zone_item.file }}

- name: Validate DNS zone
  ansible.builtin.command:
    cmd: >-
      {{ bind_service_checkzone_command }}
      {{ zone_item.zone }}
      {{ bind_service_zone_dir }}/{{ zone_item.file }}
  register: bind_service_validate_out
  changed_when: false
  failed_when: bind_service_validate_out.rc != 0
